sitecrypto/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crypto/', include('crypto.urls')),
    path('users/', include('users.urls', namespace='users')),
] + debug_toolbar_urls()

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

templates/base.html
{% load static %}
{% load crypto_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'crypto/font/main.png' %}" type="image/x-icon">
    <meta http-equiv="X-UA-Compatible">

    <title>{% block title %} {% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'crypto/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'crypto/css/main.css' %}">

    {% block css %} {% endblock %}

</head>
<body>
    <div class="container-fluid d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <img src="{% static 'crypto/font/btc.svg' %}" class="bi bi-cloud-minus" width="40" height="32">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'home' %}" class="nav-link px-2 link-dark">Main page</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'add_page' %}" methods="get" class="nav-link px-2 link-dark">Add an article</a></li>
            {% endif %}
            <li><a href="{% url 'about' %}" methods="get" class="nav-link px-2 link-dark">About the site</a></li>
            <li><a href="{% url 'contact' %}" methods="get" class="nav-link px-2 link-dark">Contact</a></li>
        </ul>
        <div class="nav">
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3 nav-link px-2 link-dark" action="{% url 'search_post' %}">
                <input type="search" class="form-control" placeholder="Cryptocurrency Search" aria-label="Search" name="search">
            </form>
            {% if user.is_authenticated %}
            <p class="nav-link px-2 link-dark">{{ user.username }}</p>
            <a href="{% url 'users:logout' %}" methods="get" class="nav-link px-2 link-dark">Logout</a>
            {% else %}
            <a href="{% url 'users:login' %}" methods="get" class="nav-link px-2 link-dark">Login</a>
            {% endif %}
        </div>
    </div>
    <hr>

<div class="container-fluid pb-5">
    <div class="d-grid gap-3" style="grid-template-columns: 0fr 5fr;">
        <div class="bg-color col mx-auto p-4 d-flex flex-column position-static">
            <h3 class="text-center">Networks:</h3>
            <ol class="list-unstyled mb-0">
                {% if network_selected == 0 %}
		            <li class="selected">All networks</li>
		        {% else %}
		            <li><a class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" href="{% url 'home' %}">All networks</a></li>
		        {% endif %}

		        {% show_networks network_selected %}

            </ol>
        </div>
    <div class="bg-color col p-4 d-flex flex-column position-static">
        {% block content %} {% endblock %}
    </div>
    </div>
</div>

{% block navigation %} {% endblock %}

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="{% static 'crypto/js/bootstrap.bundle.min.js' %}"></script>

{% block script %} {% endblock %}

</body>
</html>